/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d9e2ff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb692",
        "secondary": "#005faf",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#341100",
        "surface-variant": "#e1e3e4",
        "outline-variant": "#c3c6d4",
        "on-error-container": "#93000a",
        "inverse-primary": "#b0c6ff",
        "error-container": "#ffdad6",
        "surface-dim": "#d9dadb",
        "on-tertiary-fixed-variant": "#7a3000",
        "on-surface-variant": "#434652",
        "secondary-container": "#54a0fe",
        "background": "#f8f9fa",
        "tertiary": "#5e2300",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-container": "#a1bbff",
        "surface-bright": "#f8f9fa",
        "secondary-fixed-dim": "#a5c8ff",
        "on-background": "#191c1d",
        "on-primary-fixed-variant": "#00429c",
        "on-primary-fixed": "#001945",
        "outline": "#737783",
        "on-primary": "#ffffff",
        "surface": "#f8f9fa",
        "on-surface": "#191c1d",
        "surface-tint": "#2b5bb5",
        "surface-container-high": "#e7e8e9",
        "primary-container": "#0d47a1",
        "on-secondary-fixed": "#001c3a",
        "on-secondary-container": "#003567",
        "tertiary-container": "#823400",
        "primary": "#003178",
        "surface-container": "#edeeef",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-container": "#ffa87c",
        "on-secondary-fixed-variant": "#004786",
        "surface-container-low": "#f3f4f5",
        "primary-fixed-dim": "#b0c6ff",
        "tertiary-fixed": "#ffdbcb",
        "secondary-fixed": "#d4e3ff"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
    },
  },
  plugins: [],
}
